"""Registry of every synthetic dataset and its data-generating process (DGP).

Each entry records the file name, the generator function, the sample size,
the seed, the column schema, and the *true* parameter values used to simulate
the data. The registry is the single source of truth for:

* ``scripts/build_manifest.py`` / ``scripts/verify_manifest.py`` – integrity
  hashes for every CSV;
* ``scripts/generate_data_dictionary.py`` – ``docs/DATA_DICTIONARY.md``;
* ``scripts/parameter_recovery.py`` – fits the intended model to each dataset
  and checks that the true parameters lie inside the confidence intervals.

Datasets whose generator does not reseed inherit the module-level
``np.random.seed(42)`` and therefore depend on the order in which
``generate_all_datasets`` calls the generators. That order is recorded in
``ORDER_DEPENDENT`` and must not be changed without rebuilding the manifest.
"""

from __future__ import annotations

DATASETS: dict[str, dict] = {
    "ols_data": {
        "file": "ols_data.csv",
        "generator": "generate_ols_data",
        "n": 200,
        "seed": "module (42, order-dependent)",
        "description": "Clean multiple linear regression with two Gaussian predictors and homoskedastic noise.",
        "columns": {"X1": "N(5, 2) predictor", "X2": "N(10, 3) predictor", "y": "response"},
        "dgp": "y = 2 + 1.5 X1 - 0.7 X2 + e,  e ~ N(0, 1.5^2)",
        "true_params": {"Intercept": 2.0, "X1": 1.5, "X2": -0.7, "sigma": 1.5},
        "intended_models": ["OLS"],
    },
    "glm_poisson": {
        "file": "glm_poisson.csv",
        "generator": "generate_glm_data",
        "n": 300,
        "seed": "module (42, order-dependent)",
        "description": "Poisson counts with a log link and one predictor.",
        "columns": {"X": "N(2, 1) predictor", "y": "Poisson count"},
        "dgp": "y ~ Poisson(exp(0.5 + 0.9 X))",
        "true_params": {"Intercept": 0.5, "X": 0.9},
        "intended_models": ["GLM Poisson"],
    },
    "glm_logistic": {
        "file": "glm_logistic.csv",
        "generator": "generate_glm_data",
        "n": 300,
        "seed": "module (42, order-dependent)",
        "description": "Bernoulli outcomes with a logit link and one predictor.",
        "columns": {"X": "N(0, 1) predictor", "y": "binary outcome"},
        "dgp": "P(y = 1) = logistic(-0.5 + 0.8 X)",
        "true_params": {"Intercept": -0.5, "X": 0.8},
        "intended_models": ["Logit", "GLM Binomial"],
    },
    "arima_series": {
        "file": "arima_series.csv",
        "generator": "generate_time_series_data",
        "n": 250,
        "seed": "module (42, order-dependent)",
        "description": "Daily ARMA(1,1) series.",
        "columns": {"t": "daily date index from 2020-01-01", "value": "ARMA(1,1) realisation"},
        "dgp": "y_t = 0.8 y_{t-1} + e_t + 0.4 e_{t-1},  e ~ N(0, 1)",
        "true_params": {"ar.L1": 0.8, "ma.L1": 0.4, "sigma2": 1.0},
        "intended_models": ["ARIMA(1,0,1)"],
    },
    "manova_data": {
        "file": "manova_data.csv",
        "generator": "generate_manova_data",
        "n": 300,
        "seed": "module (42, order-dependent)",
        "description": "Two bivariate-normal groups with a mean shift of 2 on both responses.",
        "columns": {"Y1": "response 1", "Y2": "response 2", "group": "A or B (150 each)"},
        "dgp": "A ~ MVN([0, 0], [[1, .5], [.5, 1]]);  B ~ MVN([2, 2], same cov)",
        "true_params": {"mean_diff_Y1": 2.0, "mean_diff_Y2": 2.0, "corr": 0.5},
        "intended_models": ["MANOVA", "Hotelling T2"],
    },
    "heteroskedastic_data": {
        "file": "heteroskedastic_data.csv",
        "generator": "generate_heteroskedastic_data",
        "n": 200,
        "seed": "module (42, order-dependent)",
        "description": "Linear mean with error variance growing in |X|; for WLS and robust SEs.",
        "columns": {"X": "N(0, 1) predictor", "y": "response"},
        "dgp": "y = 3 + 2 X + e,  e ~ N(0, (1 + 2|X|)^2)",
        "true_params": {"Intercept": 3.0, "X": 2.0},
        "intended_models": ["OLS + HC3", "WLS"],
    },
    "multivariate_group_data": {
        "file": "multivariate_group_data.csv",
        "generator": "generate_multivariate_group_data",
        "n": 1000,
        "seed": 42,
        "description": "Five numeric and five categorical columns across two groups with different distributions.",
        "columns": {"Num1": "A: N(50,10); B: N(60,15)", "Num2": "A: U(10,100); B: U(20,120)", "Num3": "A: LogN(3,.5); B: LogN(4,.8)", "Num4": "A: Exp(1.5); B: Exp(1.0)", "Num5": "A: N(0,50); B: N(20,60)", "Group": "A/B", "Cat1-Cat5": "independent categorical noise"},
        "dgp": "group-specific marginal distributions, independent columns",
        "true_params": {"Num1_mean_A": 50.0, "Num1_mean_B": 60.0, "Num5_mean_A": 0.0, "Num5_mean_B": 20.0},
        "intended_models": ["descriptives", "t-tests", "Hotelling T2"],
    },
    "ols_diagnostics": {
        "file": "ols_diagnostics.csv",
        "generator": "generate_ols_diagnostics_data",
        "n": 600,
        "seed": 42,
        "description": "Ten predictors with multicollinearity (X6~X1, X7~X2), irrelevant predictors, and 10 injected outliers.",
        "columns": {"X1": "N(50,10)", "X2": "N(30,5)", "X3": "U(10,100)", "X4": "Exp(1.2)", "X5": "N(0,20)", "X6": "0.5 X1 + N(0,2)", "X7": "-0.4 X2 + N(0,1.5)", "X8": "N(0,1)", "X9": "U(0,1)", "X10": "Chi2(2)", "y": "response"},
        "dgp": "y = 5 + 1.5 X1 - 2 X2 + 0.3 X3 + e, e ~ N(0,10^2); 10 rows get +N(100, 20)",
        "true_params": {"Intercept": 5.0, "X1": 1.5, "X2": -2.0, "X3": 0.3},
        "intended_models": ["OLS diagnostics", "RLM"],
    },
    "posthoc_dataset": {
        "file": "posthoc_dataset.csv",
        "generator": "generate_posthoc_data",
        "n": 300,
        "seed": 42,
        "description": "Three groups of 100 with different means and variances for ANOVA and post-hoc tests.",
        "columns": {"Group": "A/B/C", "Score": "response"},
        "dgp": "A ~ N(60, 10), B ~ N(70, 12), C ~ N(65, 8)",
        "true_params": {"mean_A": 60.0, "mean_B": 70.0, "mean_C": 65.0},
        "intended_models": ["one-way ANOVA", "Tukey HSD"],
    },
    "robust_regression_data": {
        "file": "robust_regression_data.csv",
        "generator": "generate_robust_regression_data",
        "n": 200,
        "seed": 42,
        "description": "Linear relationship with heteroskedastic noise and 15 injected +/-30 outliers; includes inverse-variance weights.",
        "columns": {"X": "N(10, 3)", "y": "response", "weights": "1 / (0.5 + 0.3|X|)"},
        "dgp": "y = 5 + 2.5 X + e, e ~ N(0, (0.5 + 0.3|X|)^2); 15 rows +/- 30",
        "true_params": {"Intercept": 5.0, "X": 2.5},
        "intended_models": ["RLM (Huber)", "WLS", "Quantile regression"],
    },
    "seasonal_ts_data": {
        "file": "seasonal_ts_data.csv",
        "generator": "generate_seasonal_ts_data",
        "n": 365,
        "seed": 42,
        "description": "Trend + period-12 sinusoid + noise with an independent exogenous regressor.",
        "columns": {"t": "daily date", "y": "series", "exog": "N(5, 1.5), unrelated to y"},
        "dgp": "y_t = 50 + 0.05 t + 10 sin(2 pi t / 12) + e_t, e ~ N(0, 4)",
        "true_params": {"level": 50.0, "trend": 0.05, "amplitude": 10.0, "period": 12, "sigma": 2.0, "exog_effect": 0.0},
        "intended_models": ["SARIMAX", "harmonic regression"],
    },
    "panel_data": {
        "file": "panel_data.csv",
        "generator": "generate_panel_data",
        "n": 500,
        "seed": 42,
        "description": "Balanced panel: 50 individuals x 10 periods with individual random intercepts.",
        "columns": {"individual": "ID_0..ID_49", "time": "0..9", "X1": "N(10, 2)", "X2": "N(5, 1.5)", "y": "response"},
        "dgp": "y_it = 10 + u_i + 1.5 X1 - 0.8 X2 + e_it, u_i ~ N(0, 25), e ~ N(0, 1)",
        "true_params": {"Intercept": 10.0, "X1": 1.5, "X2": -0.8, "sd_individual": 5.0, "sigma": 1.0},
        "intended_models": ["fixed effects", "random effects / MixedLM"],
    },
    "survival_data": {
        "file": "survival_data.csv",
        "generator": "generate_survival_data",
        "n": 200,
        "seed": 42,
        "description": "Exponential survival times with covariate-dependent hazard and uniform censoring.",
        "columns": {"age": "N(55, 12)", "treatment": "Bernoulli(0.5)", "biomarker": "N(100, 20)", "time": "min(T, C)", "event": "1 if T <= C"},
        "dgp": "T ~ Exp(rate = exp(-3 + 0.02 age - 0.5 treatment + 0.01 biomarker)); C ~ U(0, 15)",
        "true_params": {"age": 0.02, "treatment": -0.5, "biomarker": 0.01},
        "intended_models": ["Cox PH", "Kaplan-Meier", "Weibull AFT"],
    },
    "zero_inflated_count": {
        "file": "zero_inflated_count.csv",
        "generator": "generate_zero_inflated_count_data",
        "n": 300,
        "seed": 42,
        "description": "Zero-inflated Poisson: structural zeros driven by x3, counts driven by x1 and x2.",
        "columns": {"x1": "N(2, 1)", "x2": "N(0, 1.5)", "x3": "N(-1, 0.8) inflation predictor", "y": "count"},
        "dgp": "P(structural zero) = logistic(-0.5 + 0.7 x3); y ~ Poisson(exp(0.5 + 0.6 x1 + 0.3 x2)) otherwise",
        "true_params": {"Intercept": 0.5, "x1": 0.6, "x2": 0.3, "inflate_Intercept": -0.5, "inflate_x3": 0.7},
        "intended_models": ["ZIP", "ZINB"],
    },
    "var_data": {
        "file": "var_data.csv",
        "generator": "generate_var_data",
        "n": 250,
        "seed": 42,
        "description": "Bivariate VAR(1) with cross-lag feedback.",
        "columns": {"t": "daily date", "y1": "series 1", "y2": "series 2"},
        "dgp": "y1_t = 0.5 y1_{t-1} + 0.2 y2_{t-1} + e1;  y2_t = 0.3 y1_{t-1} + 0.6 y2_{t-1} + e2",
        "true_params": {"L1.y1->y1": 0.5, "L1.y2->y1": 0.2, "L1.y1->y2": 0.3, "L1.y2->y2": 0.6},
        "intended_models": ["VAR(1)", "Granger causality"],
    },
    "gee_data": {
        "file": "gee_data.csv",
        "generator": "generate_gee_data",
        "n": 250,
        "seed": 42,
        "description": "50 clusters x 5 binary outcomes with a large cluster random effect (sd 3).",
        "columns": {"cluster": "C_0..C_49", "observation": "0..4", "X": "N(5, 2)", "treatment": "Bernoulli(0.5)", "y": "binary"},
        "dgp": "logit P(y=1) = -1 + 0.5 X + 0.8 treatment + u_c, u_c ~ N(0, 9)",
        "true_params": {"Intercept": -1.0, "X": 0.5, "treatment": 0.8, "sd_cluster": 3.0},
        "intended_models": ["GEE (exchangeable)", "mixed logit"],
        "note": "GEE estimates population-averaged effects, which are attenuated relative to these conditional (subject-specific) parameters.",
    },
    "mediation_data": {
        "file": "mediation_data.csv",
        "generator": "generate_mediation_data",
        "n": 300,
        "seed": 42,
        "description": "Simple mediation X -> M -> Y plus a separate moderated outcome.",
        "columns": {"X": "N(0, 1)", "M": "mediator", "Y": "outcome", "W": "N(0, 1) moderator", "Y_moderated": "moderated outcome"},
        "dgp": "M = 0.7 X + N(0, .25); Y = 0.4 X + 0.6 M + N(0, .64); Y_mod = 0.5 X + 0.3 W + 0.4 X W + N(0, .64)",
        "true_params": {"a": 0.7, "b": 0.6, "c_prime": 0.4, "indirect": 0.42, "mod_X": 0.5, "mod_W": 0.3, "mod_XW": 0.4},
        "intended_models": ["mediation (bootstrap)", "moderation"],
    },
}

ORDER_DEPENDENT = ["generate_ols_data", "generate_glm_data", "generate_time_series_data", "generate_manova_data", "generate_heteroskedastic_data"]
